name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/actions-api:latest .

      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/actions-api:latest

      - name: Deploy to GCP VM
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.GCP_SSH_USERNAME }}@${{ secrets.GCP_VM_IP }} << 'EOF'
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/actions-api:latest
          sudo docker stop actions-api || true
          sudo docker rm actions-api || true
          sudo docker run -d --name actions-api \
            -p 8001:8001 \
            --env-file /home/itspawanlive/.env \
            ${{ secrets.DOCKER_USERNAME }}/actions-api:latest
          exit
          EOF
